//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAW.Repo2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    internal class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Repo2.Repo2Soap")]
    internal interface Repo2Soap {
        
        // CODEGEN: Generating message contract since element name strSoftware from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Check", ReplyAction="*")]
        SAW.Repo2.CheckResponse Check(SAW.Repo2.CheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Check", ReplyAction="*")]
        System.Threading.Tasks.Task<SAW.Repo2.CheckResponse> CheckAsync(SAW.Repo2.CheckRequest request);
        
        // CODEGEN: Generating message contract since element name strSoftware from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Products", ReplyAction="*")]
        SAW.Repo2.ProductsResponse Products(SAW.Repo2.ProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Products", ReplyAction="*")]
        System.Threading.Tasks.Task<SAW.Repo2.ProductsResponse> ProductsAsync(SAW.Repo2.ProductsRequest request);
        
        // CODEGEN: Generating message contract since element name strSoftware from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Versions", ReplyAction="*")]
        SAW.Repo2.VersionsResponse Versions(SAW.Repo2.VersionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Versions", ReplyAction="*")]
        System.Threading.Tasks.Task<SAW.Repo2.VersionsResponse> VersionsAsync(SAW.Repo2.VersionsRequest request);
        
        // CODEGEN: Generating message contract since element name strSoftware from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LastVersionB", ReplyAction="*")]
        SAW.Repo2.LastVersionBResponse LastVersionB(SAW.Repo2.LastVersionBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LastVersionB", ReplyAction="*")]
        System.Threading.Tasks.Task<SAW.Repo2.LastVersionBResponse> LastVersionBAsync(SAW.Repo2.LastVersionBRequest request);
        
        // CODEGEN: Generating message contract since element name software from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VersionNeeds", ReplyAction="*")]
        SAW.Repo2.VersionNeedsResponse VersionNeeds(SAW.Repo2.VersionNeedsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VersionNeeds", ReplyAction="*")]
        System.Threading.Tasks.Task<SAW.Repo2.VersionNeedsResponse> VersionNeedsAsync(SAW.Repo2.VersionNeedsRequest request);
        
        // CODEGEN: Generating message contract since element name software from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreError", ReplyAction="*")]
        SAW.Repo2.StoreErrorResponse StoreError(SAW.Repo2.StoreErrorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreError", ReplyAction="*")]
        System.Threading.Tasks.Task<SAW.Repo2.StoreErrorResponse> StoreErrorAsync(SAW.Repo2.StoreErrorRequest request);
        
        // CODEGEN: Generating message contract since element name software from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Store", ReplyAction="*")]
        SAW.Repo2.StoreResponse Store(SAW.Repo2.StoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Store", ReplyAction="*")]
        System.Threading.Tasks.Task<SAW.Repo2.StoreResponse> StoreAsync(SAW.Repo2.StoreRequest request);
        
        // CODEGEN: Generating message contract since element name software from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Merge", ReplyAction="*")]
        SAW.Repo2.MergeResponse Merge(SAW.Repo2.MergeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Merge", ReplyAction="*")]
        System.Threading.Tasks.Task<SAW.Repo2.MergeResponse> MergeAsync(SAW.Repo2.MergeRequest request);
        
        // CODEGEN: Generating message contract since element name software from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyVersion", ReplyAction="*")]
        SAW.Repo2.VerifyVersionResponse VerifyVersion(SAW.Repo2.VerifyVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<SAW.Repo2.VerifyVersionResponse> VerifyVersionAsync(SAW.Repo2.VerifyVersionRequest request);
        
        // CODEGEN: Generating message contract since element name strSoftware from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        SAW.Repo2.DeleteResponse Delete(SAW.Repo2.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<SAW.Repo2.DeleteResponse> DeleteAsync(SAW.Repo2.DeleteRequest request);
        
        // CODEGEN: Generating message contract since element name strSoftware from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fetch", ReplyAction="*")]
        SAW.Repo2.FetchResponse Fetch(SAW.Repo2.FetchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Fetch", ReplyAction="*")]
        System.Threading.Tasks.Task<SAW.Repo2.FetchResponse> FetchAsync(SAW.Repo2.FetchRequest request);
        
        // CODEGEN: Generating message contract since element name strSoftware from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FetchChunk", ReplyAction="*")]
        SAW.Repo2.FetchChunkResponse FetchChunk(SAW.Repo2.FetchChunkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FetchChunk", ReplyAction="*")]
        System.Threading.Tasks.Task<SAW.Repo2.FetchChunkResponse> FetchChunkAsync(SAW.Repo2.FetchChunkRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class CheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Check", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.CheckRequestBody Body;
        
        public CheckRequest() {
        }
        
        public CheckRequest(SAW.Repo2.CheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class CheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSoftware;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strFile;
        
        public CheckRequestBody() {
        }
        
        public CheckRequestBody(string strSoftware, string strFile) {
            this.strSoftware = strSoftware;
            this.strFile = strFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class CheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckResponse", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.CheckResponseBody Body;
        
        public CheckResponse() {
        }
        
        public CheckResponse(SAW.Repo2.CheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class CheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckResult;
        
        public CheckResponseBody() {
        }
        
        public CheckResponseBody(bool CheckResult) {
            this.CheckResult = CheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Products", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.ProductsRequestBody Body;
        
        public ProductsRequest() {
        }
        
        public ProductsRequest(SAW.Repo2.ProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class ProductsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSoftware;
        
        public ProductsRequestBody() {
        }
        
        public ProductsRequestBody(string strSoftware) {
            this.strSoftware = strSoftware;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.ProductsResponseBody Body;
        
        public ProductsResponse() {
        }
        
        public ProductsResponse(SAW.Repo2.ProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class ProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SAW.Repo2.ArrayOfString ProductsResult;
        
        public ProductsResponseBody() {
        }
        
        public ProductsResponseBody(SAW.Repo2.ArrayOfString ProductsResult) {
            this.ProductsResult = ProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class VersionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Versions", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.VersionsRequestBody Body;
        
        public VersionsRequest() {
        }
        
        public VersionsRequest(SAW.Repo2.VersionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class VersionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSoftware;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strProduct;
        
        public VersionsRequestBody() {
        }
        
        public VersionsRequestBody(string strSoftware, string strProduct) {
            this.strSoftware = strSoftware;
            this.strProduct = strProduct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class VersionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VersionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.VersionsResponseBody Body;
        
        public VersionsResponse() {
        }
        
        public VersionsResponse(SAW.Repo2.VersionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class VersionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SAW.Repo2.ArrayOfString VersionsResult;
        
        public VersionsResponseBody() {
        }
        
        public VersionsResponseBody(SAW.Repo2.ArrayOfString VersionsResult) {
            this.VersionsResult = VersionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class LastVersionBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LastVersionB", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.LastVersionBRequestBody Body;
        
        public LastVersionBRequest() {
        }
        
        public LastVersionBRequest(SAW.Repo2.LastVersionBRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class LastVersionBRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSoftware;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strProduct;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strExistingVersion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strLicenceName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool bolSupport;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strLanguage;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int intNetVersion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strMachineID;
        
        public LastVersionBRequestBody() {
        }
        
        public LastVersionBRequestBody(string strSoftware, string strProduct, string strExistingVersion, string strLicenceName, bool bolSupport, string strLanguage, int intNetVersion, string strMachineID) {
            this.strSoftware = strSoftware;
            this.strProduct = strProduct;
            this.strExistingVersion = strExistingVersion;
            this.strLicenceName = strLicenceName;
            this.bolSupport = bolSupport;
            this.strLanguage = strLanguage;
            this.intNetVersion = intNetVersion;
            this.strMachineID = strMachineID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class LastVersionBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LastVersionBResponse", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.LastVersionBResponseBody Body;
        
        public LastVersionBResponse() {
        }
        
        public LastVersionBResponse(SAW.Repo2.LastVersionBResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class LastVersionBResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LastVersionBResult;
        
        public LastVersionBResponseBody() {
        }
        
        public LastVersionBResponseBody(string LastVersionBResult) {
            this.LastVersionBResult = LastVersionBResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class VersionNeedsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VersionNeeds", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.VersionNeedsRequestBody Body;
        
        public VersionNeedsRequest() {
        }
        
        public VersionNeedsRequest(SAW.Repo2.VersionNeedsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class VersionNeedsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string software;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string product;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string version;
        
        public VersionNeedsRequestBody() {
        }
        
        public VersionNeedsRequestBody(string software, string product, string version) {
            this.software = software;
            this.product = product;
            this.version = version;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class VersionNeedsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VersionNeedsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.VersionNeedsResponseBody Body;
        
        public VersionNeedsResponse() {
        }
        
        public VersionNeedsResponse(SAW.Repo2.VersionNeedsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class VersionNeedsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SAW.Repo2.ArrayOfString VersionNeedsResult;
        
        public VersionNeedsResponseBody() {
        }
        
        public VersionNeedsResponseBody(SAW.Repo2.ArrayOfString VersionNeedsResult) {
            this.VersionNeedsResult = VersionNeedsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class StoreErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StoreError", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.StoreErrorRequestBody Body;
        
        public StoreErrorRequest() {
        }
        
        public StoreErrorRequest(SAW.Repo2.StoreErrorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class StoreErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string software;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] data;
        
        public StoreErrorRequestBody() {
        }
        
        public StoreErrorRequestBody(string software, byte[] data) {
            this.software = software;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class StoreErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StoreErrorResponse", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.StoreErrorResponseBody Body;
        
        public StoreErrorResponse() {
        }
        
        public StoreErrorResponse(SAW.Repo2.StoreErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class StoreErrorResponseBody {
        
        public StoreErrorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class StoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Store", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.StoreRequestBody Body;
        
        public StoreRequest() {
        }
        
        public StoreRequest(SAW.Repo2.StoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class StoreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string software;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string file;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] data;
        
        public StoreRequestBody() {
        }
        
        public StoreRequestBody(string software, string file, byte[] data) {
            this.software = software;
            this.file = file;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class StoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StoreResponse", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.StoreResponseBody Body;
        
        public StoreResponse() {
        }
        
        public StoreResponse(SAW.Repo2.StoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class StoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool StoreResult;
        
        public StoreResponseBody() {
        }
        
        public StoreResponseBody(bool StoreResult) {
            this.StoreResult = StoreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class MergeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Merge", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.MergeRequestBody Body;
        
        public MergeRequest() {
        }
        
        public MergeRequest(SAW.Repo2.MergeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class MergeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string software;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string file;
        
        public MergeRequestBody() {
        }
        
        public MergeRequestBody(string software, string file) {
            this.software = software;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class MergeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MergeResponse", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.MergeResponseBody Body;
        
        public MergeResponse() {
        }
        
        public MergeResponse(SAW.Repo2.MergeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class MergeResponseBody {
        
        public MergeResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class VerifyVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyVersion", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.VerifyVersionRequestBody Body;
        
        public VerifyVersionRequest() {
        }
        
        public VerifyVersionRequest(SAW.Repo2.VerifyVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class VerifyVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string software;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string product;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string version;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool checksum;
        
        public VerifyVersionRequestBody() {
        }
        
        public VerifyVersionRequestBody(string software, string product, string version, bool checksum) {
            this.software = software;
            this.product = product;
            this.version = version;
            this.checksum = checksum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class VerifyVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyVersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.VerifyVersionResponseBody Body;
        
        public VerifyVersionResponse() {
        }
        
        public VerifyVersionResponse(SAW.Repo2.VerifyVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class VerifyVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerifyVersionResult;
        
        public VerifyVersionResponseBody() {
        }
        
        public VerifyVersionResponseBody(string VerifyVersionResult) {
            this.VerifyVersionResult = VerifyVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(SAW.Repo2.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSoftware;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strFile;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(string strSoftware, string strFile) {
            this.strSoftware = strSoftware;
            this.strFile = strFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(SAW.Repo2.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class DeleteResponseBody {
        
        public DeleteResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class FetchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Fetch", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.FetchRequestBody Body;
        
        public FetchRequest() {
        }
        
        public FetchRequest(SAW.Repo2.FetchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class FetchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSoftware;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strFile;
        
        public FetchRequestBody() {
        }
        
        public FetchRequestBody(string strSoftware, string strFile) {
            this.strSoftware = strSoftware;
            this.strFile = strFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class FetchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchResponse", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.FetchResponseBody Body;
        
        public FetchResponse() {
        }
        
        public FetchResponse(SAW.Repo2.FetchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class FetchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] FetchResult;
        
        public FetchResponseBody() {
        }
        
        public FetchResponseBody(byte[] FetchResult) {
            this.FetchResult = FetchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class FetchChunkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchChunk", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.FetchChunkRequestBody Body;
        
        public FetchChunkRequest() {
        }
        
        public FetchChunkRequest(SAW.Repo2.FetchChunkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class FetchChunkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSoftware;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int intStart;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int intLength;
        
        public FetchChunkRequestBody() {
        }
        
        public FetchChunkRequestBody(string strSoftware, string strFile, int intStart, int intLength) {
            this.strSoftware = strSoftware;
            this.strFile = strFile;
            this.intStart = intStart;
            this.intLength = intLength;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class FetchChunkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchChunkResponse", Namespace="http://tempuri.org/", Order=0)]
        public SAW.Repo2.FetchChunkResponseBody Body;
        
        public FetchChunkResponse() {
        }
        
        public FetchChunkResponse(SAW.Repo2.FetchChunkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class FetchChunkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] FetchChunkResult;
        
        public FetchChunkResponseBody() {
        }
        
        public FetchChunkResponseBody(byte[] FetchChunkResult) {
            this.FetchChunkResult = FetchChunkResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface Repo2SoapChannel : SAW.Repo2.Repo2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class Repo2SoapClient : System.ServiceModel.ClientBase<SAW.Repo2.Repo2Soap>, SAW.Repo2.Repo2Soap {
        
        public Repo2SoapClient() {
        }
        
        public Repo2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Repo2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Repo2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Repo2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAW.Repo2.CheckResponse SAW.Repo2.Repo2Soap.Check(SAW.Repo2.CheckRequest request) {
            return base.Channel.Check(request);
        }
        
        public bool Check(string strSoftware, string strFile) {
            SAW.Repo2.CheckRequest inValue = new SAW.Repo2.CheckRequest();
            inValue.Body = new SAW.Repo2.CheckRequestBody();
            inValue.Body.strSoftware = strSoftware;
            inValue.Body.strFile = strFile;
            SAW.Repo2.CheckResponse retVal = ((SAW.Repo2.Repo2Soap)(this)).Check(inValue);
            return retVal.Body.CheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAW.Repo2.CheckResponse> SAW.Repo2.Repo2Soap.CheckAsync(SAW.Repo2.CheckRequest request) {
            return base.Channel.CheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAW.Repo2.CheckResponse> CheckAsync(string strSoftware, string strFile) {
            SAW.Repo2.CheckRequest inValue = new SAW.Repo2.CheckRequest();
            inValue.Body = new SAW.Repo2.CheckRequestBody();
            inValue.Body.strSoftware = strSoftware;
            inValue.Body.strFile = strFile;
            return ((SAW.Repo2.Repo2Soap)(this)).CheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAW.Repo2.ProductsResponse SAW.Repo2.Repo2Soap.Products(SAW.Repo2.ProductsRequest request) {
            return base.Channel.Products(request);
        }
        
        public SAW.Repo2.ArrayOfString Products(string strSoftware) {
            SAW.Repo2.ProductsRequest inValue = new SAW.Repo2.ProductsRequest();
            inValue.Body = new SAW.Repo2.ProductsRequestBody();
            inValue.Body.strSoftware = strSoftware;
            SAW.Repo2.ProductsResponse retVal = ((SAW.Repo2.Repo2Soap)(this)).Products(inValue);
            return retVal.Body.ProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAW.Repo2.ProductsResponse> SAW.Repo2.Repo2Soap.ProductsAsync(SAW.Repo2.ProductsRequest request) {
            return base.Channel.ProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAW.Repo2.ProductsResponse> ProductsAsync(string strSoftware) {
            SAW.Repo2.ProductsRequest inValue = new SAW.Repo2.ProductsRequest();
            inValue.Body = new SAW.Repo2.ProductsRequestBody();
            inValue.Body.strSoftware = strSoftware;
            return ((SAW.Repo2.Repo2Soap)(this)).ProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAW.Repo2.VersionsResponse SAW.Repo2.Repo2Soap.Versions(SAW.Repo2.VersionsRequest request) {
            return base.Channel.Versions(request);
        }
        
        public SAW.Repo2.ArrayOfString Versions(string strSoftware, string strProduct) {
            SAW.Repo2.VersionsRequest inValue = new SAW.Repo2.VersionsRequest();
            inValue.Body = new SAW.Repo2.VersionsRequestBody();
            inValue.Body.strSoftware = strSoftware;
            inValue.Body.strProduct = strProduct;
            SAW.Repo2.VersionsResponse retVal = ((SAW.Repo2.Repo2Soap)(this)).Versions(inValue);
            return retVal.Body.VersionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAW.Repo2.VersionsResponse> SAW.Repo2.Repo2Soap.VersionsAsync(SAW.Repo2.VersionsRequest request) {
            return base.Channel.VersionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAW.Repo2.VersionsResponse> VersionsAsync(string strSoftware, string strProduct) {
            SAW.Repo2.VersionsRequest inValue = new SAW.Repo2.VersionsRequest();
            inValue.Body = new SAW.Repo2.VersionsRequestBody();
            inValue.Body.strSoftware = strSoftware;
            inValue.Body.strProduct = strProduct;
            return ((SAW.Repo2.Repo2Soap)(this)).VersionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAW.Repo2.LastVersionBResponse SAW.Repo2.Repo2Soap.LastVersionB(SAW.Repo2.LastVersionBRequest request) {
            return base.Channel.LastVersionB(request);
        }
        
        public string LastVersionB(string strSoftware, string strProduct, string strExistingVersion, string strLicenceName, bool bolSupport, string strLanguage, int intNetVersion, string strMachineID) {
            SAW.Repo2.LastVersionBRequest inValue = new SAW.Repo2.LastVersionBRequest();
            inValue.Body = new SAW.Repo2.LastVersionBRequestBody();
            inValue.Body.strSoftware = strSoftware;
            inValue.Body.strProduct = strProduct;
            inValue.Body.strExistingVersion = strExistingVersion;
            inValue.Body.strLicenceName = strLicenceName;
            inValue.Body.bolSupport = bolSupport;
            inValue.Body.strLanguage = strLanguage;
            inValue.Body.intNetVersion = intNetVersion;
            inValue.Body.strMachineID = strMachineID;
            SAW.Repo2.LastVersionBResponse retVal = ((SAW.Repo2.Repo2Soap)(this)).LastVersionB(inValue);
            return retVal.Body.LastVersionBResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAW.Repo2.LastVersionBResponse> SAW.Repo2.Repo2Soap.LastVersionBAsync(SAW.Repo2.LastVersionBRequest request) {
            return base.Channel.LastVersionBAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAW.Repo2.LastVersionBResponse> LastVersionBAsync(string strSoftware, string strProduct, string strExistingVersion, string strLicenceName, bool bolSupport, string strLanguage, int intNetVersion, string strMachineID) {
            SAW.Repo2.LastVersionBRequest inValue = new SAW.Repo2.LastVersionBRequest();
            inValue.Body = new SAW.Repo2.LastVersionBRequestBody();
            inValue.Body.strSoftware = strSoftware;
            inValue.Body.strProduct = strProduct;
            inValue.Body.strExistingVersion = strExistingVersion;
            inValue.Body.strLicenceName = strLicenceName;
            inValue.Body.bolSupport = bolSupport;
            inValue.Body.strLanguage = strLanguage;
            inValue.Body.intNetVersion = intNetVersion;
            inValue.Body.strMachineID = strMachineID;
            return ((SAW.Repo2.Repo2Soap)(this)).LastVersionBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAW.Repo2.VersionNeedsResponse SAW.Repo2.Repo2Soap.VersionNeeds(SAW.Repo2.VersionNeedsRequest request) {
            return base.Channel.VersionNeeds(request);
        }
        
        public SAW.Repo2.ArrayOfString VersionNeeds(string software, string product, string version) {
            SAW.Repo2.VersionNeedsRequest inValue = new SAW.Repo2.VersionNeedsRequest();
            inValue.Body = new SAW.Repo2.VersionNeedsRequestBody();
            inValue.Body.software = software;
            inValue.Body.product = product;
            inValue.Body.version = version;
            SAW.Repo2.VersionNeedsResponse retVal = ((SAW.Repo2.Repo2Soap)(this)).VersionNeeds(inValue);
            return retVal.Body.VersionNeedsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAW.Repo2.VersionNeedsResponse> SAW.Repo2.Repo2Soap.VersionNeedsAsync(SAW.Repo2.VersionNeedsRequest request) {
            return base.Channel.VersionNeedsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAW.Repo2.VersionNeedsResponse> VersionNeedsAsync(string software, string product, string version) {
            SAW.Repo2.VersionNeedsRequest inValue = new SAW.Repo2.VersionNeedsRequest();
            inValue.Body = new SAW.Repo2.VersionNeedsRequestBody();
            inValue.Body.software = software;
            inValue.Body.product = product;
            inValue.Body.version = version;
            return ((SAW.Repo2.Repo2Soap)(this)).VersionNeedsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAW.Repo2.StoreErrorResponse SAW.Repo2.Repo2Soap.StoreError(SAW.Repo2.StoreErrorRequest request) {
            return base.Channel.StoreError(request);
        }
        
        public void StoreError(string software, byte[] data) {
            SAW.Repo2.StoreErrorRequest inValue = new SAW.Repo2.StoreErrorRequest();
            inValue.Body = new SAW.Repo2.StoreErrorRequestBody();
            inValue.Body.software = software;
            inValue.Body.data = data;
            SAW.Repo2.StoreErrorResponse retVal = ((SAW.Repo2.Repo2Soap)(this)).StoreError(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAW.Repo2.StoreErrorResponse> SAW.Repo2.Repo2Soap.StoreErrorAsync(SAW.Repo2.StoreErrorRequest request) {
            return base.Channel.StoreErrorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAW.Repo2.StoreErrorResponse> StoreErrorAsync(string software, byte[] data) {
            SAW.Repo2.StoreErrorRequest inValue = new SAW.Repo2.StoreErrorRequest();
            inValue.Body = new SAW.Repo2.StoreErrorRequestBody();
            inValue.Body.software = software;
            inValue.Body.data = data;
            return ((SAW.Repo2.Repo2Soap)(this)).StoreErrorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAW.Repo2.StoreResponse SAW.Repo2.Repo2Soap.Store(SAW.Repo2.StoreRequest request) {
            return base.Channel.Store(request);
        }
        
        public bool Store(string software, string file, byte[] data) {
            SAW.Repo2.StoreRequest inValue = new SAW.Repo2.StoreRequest();
            inValue.Body = new SAW.Repo2.StoreRequestBody();
            inValue.Body.software = software;
            inValue.Body.file = file;
            inValue.Body.data = data;
            SAW.Repo2.StoreResponse retVal = ((SAW.Repo2.Repo2Soap)(this)).Store(inValue);
            return retVal.Body.StoreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAW.Repo2.StoreResponse> SAW.Repo2.Repo2Soap.StoreAsync(SAW.Repo2.StoreRequest request) {
            return base.Channel.StoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAW.Repo2.StoreResponse> StoreAsync(string software, string file, byte[] data) {
            SAW.Repo2.StoreRequest inValue = new SAW.Repo2.StoreRequest();
            inValue.Body = new SAW.Repo2.StoreRequestBody();
            inValue.Body.software = software;
            inValue.Body.file = file;
            inValue.Body.data = data;
            return ((SAW.Repo2.Repo2Soap)(this)).StoreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAW.Repo2.MergeResponse SAW.Repo2.Repo2Soap.Merge(SAW.Repo2.MergeRequest request) {
            return base.Channel.Merge(request);
        }
        
        public void Merge(string software, string file) {
            SAW.Repo2.MergeRequest inValue = new SAW.Repo2.MergeRequest();
            inValue.Body = new SAW.Repo2.MergeRequestBody();
            inValue.Body.software = software;
            inValue.Body.file = file;
            SAW.Repo2.MergeResponse retVal = ((SAW.Repo2.Repo2Soap)(this)).Merge(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAW.Repo2.MergeResponse> SAW.Repo2.Repo2Soap.MergeAsync(SAW.Repo2.MergeRequest request) {
            return base.Channel.MergeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAW.Repo2.MergeResponse> MergeAsync(string software, string file) {
            SAW.Repo2.MergeRequest inValue = new SAW.Repo2.MergeRequest();
            inValue.Body = new SAW.Repo2.MergeRequestBody();
            inValue.Body.software = software;
            inValue.Body.file = file;
            return ((SAW.Repo2.Repo2Soap)(this)).MergeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAW.Repo2.VerifyVersionResponse SAW.Repo2.Repo2Soap.VerifyVersion(SAW.Repo2.VerifyVersionRequest request) {
            return base.Channel.VerifyVersion(request);
        }
        
        public string VerifyVersion(string software, string product, string version, bool checksum) {
            SAW.Repo2.VerifyVersionRequest inValue = new SAW.Repo2.VerifyVersionRequest();
            inValue.Body = new SAW.Repo2.VerifyVersionRequestBody();
            inValue.Body.software = software;
            inValue.Body.product = product;
            inValue.Body.version = version;
            inValue.Body.checksum = checksum;
            SAW.Repo2.VerifyVersionResponse retVal = ((SAW.Repo2.Repo2Soap)(this)).VerifyVersion(inValue);
            return retVal.Body.VerifyVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAW.Repo2.VerifyVersionResponse> SAW.Repo2.Repo2Soap.VerifyVersionAsync(SAW.Repo2.VerifyVersionRequest request) {
            return base.Channel.VerifyVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAW.Repo2.VerifyVersionResponse> VerifyVersionAsync(string software, string product, string version, bool checksum) {
            SAW.Repo2.VerifyVersionRequest inValue = new SAW.Repo2.VerifyVersionRequest();
            inValue.Body = new SAW.Repo2.VerifyVersionRequestBody();
            inValue.Body.software = software;
            inValue.Body.product = product;
            inValue.Body.version = version;
            inValue.Body.checksum = checksum;
            return ((SAW.Repo2.Repo2Soap)(this)).VerifyVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAW.Repo2.DeleteResponse SAW.Repo2.Repo2Soap.Delete(SAW.Repo2.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public void Delete(string strSoftware, string strFile) {
            SAW.Repo2.DeleteRequest inValue = new SAW.Repo2.DeleteRequest();
            inValue.Body = new SAW.Repo2.DeleteRequestBody();
            inValue.Body.strSoftware = strSoftware;
            inValue.Body.strFile = strFile;
            SAW.Repo2.DeleteResponse retVal = ((SAW.Repo2.Repo2Soap)(this)).Delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAW.Repo2.DeleteResponse> SAW.Repo2.Repo2Soap.DeleteAsync(SAW.Repo2.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAW.Repo2.DeleteResponse> DeleteAsync(string strSoftware, string strFile) {
            SAW.Repo2.DeleteRequest inValue = new SAW.Repo2.DeleteRequest();
            inValue.Body = new SAW.Repo2.DeleteRequestBody();
            inValue.Body.strSoftware = strSoftware;
            inValue.Body.strFile = strFile;
            return ((SAW.Repo2.Repo2Soap)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAW.Repo2.FetchResponse SAW.Repo2.Repo2Soap.Fetch(SAW.Repo2.FetchRequest request) {
            return base.Channel.Fetch(request);
        }
        
        public byte[] Fetch(string strSoftware, string strFile) {
            SAW.Repo2.FetchRequest inValue = new SAW.Repo2.FetchRequest();
            inValue.Body = new SAW.Repo2.FetchRequestBody();
            inValue.Body.strSoftware = strSoftware;
            inValue.Body.strFile = strFile;
            SAW.Repo2.FetchResponse retVal = ((SAW.Repo2.Repo2Soap)(this)).Fetch(inValue);
            return retVal.Body.FetchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAW.Repo2.FetchResponse> SAW.Repo2.Repo2Soap.FetchAsync(SAW.Repo2.FetchRequest request) {
            return base.Channel.FetchAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAW.Repo2.FetchResponse> FetchAsync(string strSoftware, string strFile) {
            SAW.Repo2.FetchRequest inValue = new SAW.Repo2.FetchRequest();
            inValue.Body = new SAW.Repo2.FetchRequestBody();
            inValue.Body.strSoftware = strSoftware;
            inValue.Body.strFile = strFile;
            return ((SAW.Repo2.Repo2Soap)(this)).FetchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SAW.Repo2.FetchChunkResponse SAW.Repo2.Repo2Soap.FetchChunk(SAW.Repo2.FetchChunkRequest request) {
            return base.Channel.FetchChunk(request);
        }
        
        public byte[] FetchChunk(string strSoftware, string strFile, int intStart, int intLength) {
            SAW.Repo2.FetchChunkRequest inValue = new SAW.Repo2.FetchChunkRequest();
            inValue.Body = new SAW.Repo2.FetchChunkRequestBody();
            inValue.Body.strSoftware = strSoftware;
            inValue.Body.strFile = strFile;
            inValue.Body.intStart = intStart;
            inValue.Body.intLength = intLength;
            SAW.Repo2.FetchChunkResponse retVal = ((SAW.Repo2.Repo2Soap)(this)).FetchChunk(inValue);
            return retVal.Body.FetchChunkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SAW.Repo2.FetchChunkResponse> SAW.Repo2.Repo2Soap.FetchChunkAsync(SAW.Repo2.FetchChunkRequest request) {
            return base.Channel.FetchChunkAsync(request);
        }
        
        public System.Threading.Tasks.Task<SAW.Repo2.FetchChunkResponse> FetchChunkAsync(string strSoftware, string strFile, int intStart, int intLength) {
            SAW.Repo2.FetchChunkRequest inValue = new SAW.Repo2.FetchChunkRequest();
            inValue.Body = new SAW.Repo2.FetchChunkRequestBody();
            inValue.Body.strSoftware = strSoftware;
            inValue.Body.strFile = strFile;
            inValue.Body.intStart = intStart;
            inValue.Body.intLength = intLength;
            return ((SAW.Repo2.Repo2Soap)(this)).FetchChunkAsync(inValue);
        }
    }
}
